"""
AETHER - autonomous publish run
Picks a topic itself, runs the full free pipeline, uploads publicly to
YouTube with CC attribution in the description, and logs the result to
jobs.json so it shows up in the dashboard too. Meant to be run headless by
Windows Task Scheduler, 4x/day.
"""
import asyncio
import logging
import sys
import time

import jobs
from pick_topic import pick_topic
from generate_script import generate_script
from fetch_footage import fetch_footage_for_scenes
from generate_voice import generate_voice_for_scenes
from assemble_video import assemble
from attribution import build_attribution_block
from upload_youtube import upload_video

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[
        logging.FileHandler("auto_publish.log"),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger("auto_publish")


def main() -> None:
    topic = pick_topic()
    log.info(f"Selected topic: {topic}")
    job_id = jobs.create_job(topic, upload=True)

    try:
        jobs.update_job(job_id, step="writing script")
        scenes = generate_script(topic)
        if not scenes:
            log.warning("Empty script on first attempt, retrying once")
            scenes = generate_script(topic)
        if not scenes:
            raise RuntimeError("Script generation returned no scenes - is Ollama running?")
        log.info(f"Script: {len(scenes)} scenes")

        jobs.update_job(job_id, step="fetching footage")
        scenes = fetch_footage_for_scenes(scenes)

        jobs.update_job(job_id, step="generating voiceover")
        scenes = asyncio.run(generate_voice_for_scenes(scenes))

        jobs.update_job(job_id, step="assembling video")
        video_path = assemble({"topic": topic, "scenes": scenes})
        jobs.update_job(job_id, video_path=video_path)
        log.info(f"Assembled: {video_path}")

        jobs.update_job(job_id, step="uploading to YouTube")
        credits = build_attribution_block(scenes)
        title = f"{topic[:80]} #Shorts"
        description = f"{topic} #Shorts #mystery\n\nGenerated by AETHER." + (f"\n\n{credits}" if credits else "")
        tags = ["mystery", "unsolved", "aviation", "documentary", "shorts"]
        video_id = upload_video(video_path, title, description, tags, privacy="public")
        jobs.update_job(job_id, youtube_url=f"https://youtu.be/{video_id}")
        log.info(f"Uploaded: https://youtu.be/{video_id}")

        jobs.update_job(job_id, status="done", step="done")
    except Exception as e:
        log.exception("auto_publish run failed")
        jobs.update_job(job_id, status="error", error=str(e))
        raise


if __name__ == "__main__":
    try:
        main()
    except Exception:
        sys.exit(1)
