"""
AETHER - local dashboard
Simple local-only webpage: type a topic, click Generate, watch it produce a
video through the free pipeline (script -> footage -> voice -> assemble ->
optional YouTube upload). Run with: venv\\Scripts\\python dashboard.py
Then open http://localhost:5000
"""
import asyncio
import os
import threading

from flask import Flask, jsonify, render_template, request

import jobs
from generate_script import generate_script
from fetch_footage import fetch_footage_for_scenes
from generate_voice import generate_voice_for_scenes
from assemble_video import assemble

app = Flask(__name__)

HAS_YOUTUBE_CREDS = os.path.exists(os.path.join(os.path.dirname(__file__), "client_secret.json"))

def run_pipeline(job_id: str, topic: str, upload: bool) -> None:
    try:
        jobs.update_job(job_id, step="writing script")
        scenes = generate_script(topic)
        if not scenes:
            scenes = generate_script(topic)
        if not scenes:
            raise RuntimeError("Script generation returned no scenes - is Ollama running?")

        jobs.update_job(job_id, step="fetching footage")
        scenes = fetch_footage_for_scenes(scenes)

        jobs.update_job(job_id, step="generating voiceover")
        scenes = asyncio.run(generate_voice_for_scenes(scenes))

        jobs.update_job(job_id, step="assembling video")
        video_path = assemble({"topic": topic, "scenes": scenes})
        jobs.update_job(job_id, video_path=video_path)

        if upload:
            jobs.update_job(job_id, step="uploading to YouTube")
            from upload_youtube import upload_video
            from attribution import build_attribution_block

            title = f"{topic[:80]} #Shorts"
            credits = build_attribution_block(scenes)
            description = f"{topic} #Shorts #mystery\n\nGenerated by AETHER." + (f"\n\n{credits}" if credits else "")
            tags = ["mystery", "unsolved", "aviation", "documentary", "shorts"]
            video_id = upload_video(video_path, title, description, tags, privacy="public")
            jobs.update_job(job_id, youtube_url=f"https://youtu.be/{video_id}")

        jobs.update_job(job_id, status="done", step="done")
    except Exception as e:
        jobs.update_job(job_id, status="error", error=str(e))


@app.route("/")
def index():
    return render_template("dashboard.html", has_youtube_creds=HAS_YOUTUBE_CREDS)


@app.route("/api/jobs")
def api_jobs():
    return jsonify(jobs.list_jobs())


@app.route("/api/generate", methods=["POST"])
def api_generate():
    data = request.get_json()
    topic = data["topic"].strip()
    upload = bool(data.get("upload")) and HAS_YOUTUBE_CREDS
    job_id = jobs.create_job(topic, upload)
    threading.Thread(target=run_pipeline, args=(job_id, topic, upload), daemon=True).start()
    return jsonify({"job_id": job_id})


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=False)
