"""
AETHER - main orchestrator (cheapest-possible edition)
topic -> local-LLM script -> free NASA footage -> free TTS voiceover ->
assembled mp4 -> (optional) YouTube upload.

Usage:
  venv\\Scripts\\python main.py "black holes"
  venv\\Scripts\\python main.py "black holes" --upload
"""
import asyncio
import json
import sys

from generate_script import generate_script
from fetch_footage import fetch_footage_for_scenes
from generate_voice import generate_voice_for_scenes
from assemble_video import assemble


def run(topic: str, upload: bool) -> dict:
    print(f"[1/4] Writing script for '{topic}' (local LLM, free)...", file=sys.stderr)
    scenes = generate_script(topic)
    if not scenes:
        raise SystemExit("Script generation failed - check Ollama is running (ollama serve) and model is pulled.")
    print(f"      {len(scenes)} scenes written.", file=sys.stderr)

    print("[2/4] Fetching NASA footage (free, public domain)...", file=sys.stderr)
    scenes = fetch_footage_for_scenes(scenes)

    print("[3/4] Generating voiceover (free neural TTS)...", file=sys.stderr)
    scenes = asyncio.run(generate_voice_for_scenes(scenes))

    print("[4/4] Assembling final video...", file=sys.stderr)
    data = {"topic": topic, "scenes": scenes}
    video_path = assemble(data)
    print(f"Done: {video_path}", file=sys.stderr)

    result = {"topic": topic, "video_path": video_path}

    if upload:
        print("Uploading to YouTube (private)...", file=sys.stderr)
        from upload_youtube import upload_video

        title = f"{topic.title()} - Explained"
        description = f"An AI-narrated short documentary about {topic}, built with free NASA public-domain imagery.\n\nGenerated by AETHER."
        tags = [w for w in topic.split() if w] + ["space", "science", "documentary"]
        video_id = upload_video(video_path, title, description, tags, privacy="private")
        result["youtube_url"] = f"https://youtu.be/{video_id}"
        print(f"Uploaded (private): {result['youtube_url']}", file=sys.stderr)

    return result


if __name__ == "__main__":
    args = sys.argv[1:]
    upload = "--upload" in args
    args = [a for a in args if a != "--upload"]
    topic = " ".join(args) or "black holes"

    result = run(topic, upload)
    print(json.dumps(result, indent=2))
