"""One-off: regenerate and publish a specific topic that failed, using the
current pipeline (grounded script, caption cards, ambient music, thumbnail)."""
import asyncio
import sys

import jobs
from generate_script import generate_script
from fetch_footage import fetch_footage_for_scenes
from generate_voice import generate_voice_for_scenes
from assemble_video import assemble
from attribution import build_attribution_block
from upload_youtube import upload_video, set_thumbnail
from thumbnail import generate_thumbnail

TOPIC = sys.argv[1] if len(sys.argv) > 1 else "the Bermuda Triangle and how it works"


def run(topic: str) -> None:
    job_id = jobs.create_job(topic, upload=True)
    try:
        jobs.update_job(job_id, step="writing script")
        scenes = generate_script(topic)
        if not scenes:
            scenes = generate_script(topic)
        if not scenes:
            raise RuntimeError("empty script twice")

        jobs.update_job(job_id, step="fetching footage")
        scenes = fetch_footage_for_scenes(scenes)

        jobs.update_job(job_id, step="generating voiceover")
        scenes = asyncio.run(generate_voice_for_scenes(scenes))

        jobs.update_job(job_id, step="assembling video")
        video_path = assemble({"topic": topic, "scenes": scenes})
        jobs.update_job(job_id, video_path=video_path)

        jobs.update_job(job_id, step="uploading to YouTube")
        credits = build_attribution_block(scenes)
        title = f"{topic[:80]} #Shorts"
        description = f"{topic} #Shorts #mystery\n\nGenerated by AETHER." + (f"\n\n{credits}" if credits else "")
        tags = ["mystery", "unsolved", "aviation", "documentary", "shorts"]
        video_id = upload_video(video_path, title, description, tags, privacy="public")
        jobs.update_job(job_id, youtube_url=f"https://youtu.be/{video_id}")

        jobs.update_job(job_id, step="setting thumbnail")
        thumb_path = generate_thumbnail(topic, scenes)
        if thumb_path:
            set_thumbnail(video_id, thumb_path)

        jobs.update_job(job_id, status="done", step="done")
        print(f"OK: {topic} -> https://youtu.be/{video_id}")
    except Exception as e:
        jobs.update_job(job_id, status="error", error=str(e))
        print(f"FAILED: {topic} -> {e}")
        raise


if __name__ == "__main__":
    run(TOPIC)
