"""One-off: retry specific topics that failed in a batch run, bypassing pick_topic."""
import asyncio
import sys

import jobs
from generate_script import generate_script
from fetch_footage import fetch_footage_for_scenes
from generate_voice import generate_voice_for_scenes
from assemble_video import assemble
from attribution import build_attribution_block
from upload_youtube import upload_video

TOPICS = [
    "the Lake Michigan Northwest Airlines Flight 2501 disappearance",
    "the Mary Celeste ghost ship",
    "the Zanzibar radar ghost plane incident",
]


def run(topic: str) -> None:
    job_id = jobs.create_job(topic, upload=True)
    try:
        jobs.update_job(job_id, step="writing script")
        scenes = generate_script(topic)
        if not scenes:
            scenes = generate_script(topic)
        if not scenes:
            raise RuntimeError("empty script twice")

        jobs.update_job(job_id, step="fetching footage")
        scenes = fetch_footage_for_scenes(scenes)

        jobs.update_job(job_id, step="generating voiceover")
        scenes = asyncio.run(generate_voice_for_scenes(scenes))

        jobs.update_job(job_id, step="assembling video")
        video_path = assemble({"topic": topic, "scenes": scenes})
        jobs.update_job(job_id, video_path=video_path)

        jobs.update_job(job_id, step="uploading to YouTube")
        credits = build_attribution_block(scenes)
        title = f"{topic[:80]} #Shorts"
        description = f"{topic} #Shorts #mystery\n\nGenerated by AETHER." + (f"\n\n{credits}" if credits else "")
        tags = ["mystery", "unsolved", "aviation", "documentary", "shorts"]
        video_id = upload_video(video_path, title, description, tags, privacy="public")
        jobs.update_job(job_id, youtube_url=f"https://youtu.be/{video_id}")
        jobs.update_job(job_id, status="done", step="done")
        print(f"OK: {topic} -> https://youtu.be/{video_id}")
    except Exception as e:
        jobs.update_job(job_id, status="error", error=str(e))
        print(f"FAILED again: {topic} -> {e}")


if __name__ == "__main__":
    for t in TOPICS:
        run(t)
