"""
AETHER - YouTube uploader
Uploads the finished mp4 via the free YouTube Data API v3.

One-time setup required (free, no paid tier needed):
1. Go to https://console.cloud.google.com/ , create a project.
2. Enable "YouTube Data API v3" for that project (APIs & Services > Library).
3. APIs & Services > Credentials > Create Credentials > OAuth client ID.
   - Application type: Desktop app
   - Download the JSON, save it as aether/client_secret.json
4. First run will open a browser window for you to sign in and grant access.
   A token.json is cached afterwards so you won't need to sign in again.
"""
import json
import os
import sys

from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

SCOPES = [
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube.readonly",
    "https://www.googleapis.com/auth/yt-analytics.readonly",
]
BASE_DIR = os.path.dirname(__file__)
CLIENT_SECRET_FILE = os.path.join(BASE_DIR, "client_secret.json")
TOKEN_FILE = os.path.join(BASE_DIR, "token.json")


def get_credentials(client_secret_file: str = CLIENT_SECRET_FILE, token_file: str = TOKEN_FILE) -> Credentials:
    creds = None
    if os.path.exists(token_file):
        creds = Credentials.from_authorized_user_file(token_file, SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists(client_secret_file):
                raise SystemExit(
                    f"Missing {client_secret_file}. See the setup steps in this file's docstring."
                )
            flow = InstalledAppFlow.from_client_secrets_file(client_secret_file, SCOPES)
            creds = flow.run_local_server(port=0)
        with open(token_file, "w") as f:
            f.write(creds.to_json())
    return creds


def upload_video(
    video_path: str,
    title: str,
    description: str,
    tags: list[str],
    privacy: str = "private",
    client_secret_file: str = CLIENT_SECRET_FILE,
    token_file: str = TOKEN_FILE,
    category_id: str = "27",
    made_for_kids: bool = False,
) -> str:
    creds = get_credentials(client_secret_file, token_file)
    youtube = build("youtube", "v3", credentials=creds)

    body = {
        "snippet": {
            "title": title[:100],
            "description": description[:5000],
            "tags": tags,
            "categoryId": category_id,
        },
        "status": {
            "privacyStatus": privacy,  # "private" by default - flip to "public" once you trust it
            "selfDeclaredMadeForKids": made_for_kids,
        },
    }

    media = MediaFileUpload(video_path, chunksize=-1, resumable=True, mimetype="video/mp4")
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"Upload progress: {int(status.progress() * 100)}%", file=sys.stderr)

    return response["id"]


def set_thumbnail(
    video_id: str,
    thumbnail_path: str,
    client_secret_file: str = CLIENT_SECRET_FILE,
    token_file: str = TOKEN_FILE,
) -> None:
    """Best-effort - custom thumbnails require the channel to be verified,
    so this logs and moves on rather than failing the whole publish if it's
    rejected."""
    try:
        creds = get_credentials(client_secret_file, token_file)
        youtube = build("youtube", "v3", credentials=creds)
        media = MediaFileUpload(thumbnail_path, mimetype="image/jpeg")
        youtube.thumbnails().set(videoId=video_id, media_body=media).execute()
    except Exception as e:
        print(f"Custom thumbnail upload failed (non-fatal): {e}", file=sys.stderr)


if __name__ == "__main__":
    data = json.load(sys.stdin)
    topic = data["topic"]
    video_path = data["video_path"]

    title = f"{topic.title()} - Explained"
    description = (
        f"An AI-narrated short documentary about {topic}, built with free NASA public-domain imagery.\n\n"
        f"Generated by AETHER."
    )
    tags = [w for w in topic.split() if w] + ["space", "science", "documentary"]

    video_id = upload_video(video_path, title, description, tags, privacy="private")
    print(json.dumps({"video_id": video_id, "url": f"https://youtu.be/{video_id}"}, indent=2))
